const fs = require('fs');
const BASE = 'D:/project/ai-test-agent/backend/workspace/testcase/';
const f1 = JSON.parse(fs.readFileSync(BASE + 'modules_1_2_4_5.json', 'utf-8'));
const f2 = JSON.parse(fs.readFileSync(BASE + 'merged_all_test_cases_final.json', 'utf-8'));
const merged = f1.concat(f2);
console.log('Total:', merged.length);
const json = JSON.stringify(merged, null, 2);
fs.writeFileSync(BASE + 'all_137_test_cases.json', json, 'utf-8');
console.log('Written, size:', json.length);
const v = JSON.parse(fs.readFileSync(BASE + 'all_137_test_cases.json', 'utf-8'));
console.log('Verified:', v.length);
