"""add_test_run_execution_fields

Revision ID: ef7cb920f923
Revises: a1b2c3d4e5f7
Create Date: 2026-07-13 05:51:04.658540+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7cb920f923'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 仅补充缺失的 failure_policy 字段；其余 execution_mode/max_concurrency/
    # trigger_type/scheduled_by/environment_id 已通过其他途径存在于表中。
    op.add_column(
        'test_runs',
        sa.Column(
            'failure_policy',
            sa.Enum('continue', 'stop_run', 'stop_job', 'mark_blocked', name='failurepolicy'),
            server_default='continue',
            nullable=False,
            comment='失败策略: continue / stop_run / stop_job / mark_blocked',
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'failure_policy')
    # ### end Alembic commands ###
