"""drop_auth_credentials_encrypted

Revision ID: 9b1d3e7f2a84
Revises: 8f4a2c1d5e90
Create Date: 2026-07-08 10:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9b1d3e7f2a84'
down_revision: Union[str, None] = '8f4a2c1d5e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_environments', 'auth_credentials_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import sa
    op.add_column(
        'project_environments',
        sa.Column(
            'auth_credentials_encrypted',
            sa.Text(),
            nullable=True,
            comment='加密后的认证原材料（如动态登录账号密码、OAuth2 client_secret）'
        )
    )
    # ### end Alembic commands ###
