"""rename_auth_secret_and_drop_headers

Revision ID: 7c2f8a1e3b95
Revises: 9b1d3e7f2a84
Create Date: 2026-07-08 11:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7c2f8a1e3b95'
down_revision: Union[str, None] = '9b1d3e7f2a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 将加密的 auth_secret_encrypted 重命名为 auth_secret（后续按明文使用）
    op.alter_column('project_environments', 'auth_secret_encrypted', new_column_name='auth_secret')
    # 删除额外请求头字段
    op.drop_column('project_environments', 'headers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import sa
    op.alter_column('project_environments', 'auth_secret', new_column_name='auth_secret_encrypted')
    op.add_column(
        'project_environments',
        sa.Column('headers', sa.JSON(), nullable=False, server_default='{}')
    )
    # ### end Alembic commands ###
