"""add_web_test_run_stdout_stderr

Revision ID: 07cf36d34e86
Revises: ef7cb920f923
Create Date: 2026-07-13 06:30:42.015674+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07cf36d34e86'
down_revision: Union[str, None] = 'ef7cb920f923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'web_test_runs',
        sa.Column(
            'stdout',
            sa.Text(),
            nullable=True,
            comment='标准输出日志',
        )
    )
    op.add_column(
        'web_test_runs',
        sa.Column(
            'stderr',
            sa.Text(),
            nullable=True,
            comment='标准错误日志',
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_test_runs', 'stderr')
    op.drop_column('web_test_runs', 'stdout')
    # ### end Alembic commands ###
