"""add_variable_exports_to_scenario_steps

Revision ID: 27a86ed6d63e
Revises: fdb7f7eb4aec
Create Date: 2026-07-21 03:36:25.498349+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27a86ed6d63e'
down_revision: Union[str, None] = 'fdb7f7eb4aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'scenario_steps',
        sa.Column(
            'variable_exports',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='[]',
            nullable=False,
            comment='步骤变量导出配置：将请求/响应值导出到上下文供后续步骤引用',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_steps', 'variable_exports')
    # ### end Alembic commands ###
