"""add_test_run_environment_id

Revision ID: a1b2c3d4e5f6
Revises: e3ab9597b6a7
Create Date: 2026-07-10 10:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'e3ab9597b6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'test_runs',
        sa.Column(
            'environment_id',
            postgresql.UUID(as_uuid=True),
            nullable=True,
            comment='执行环境 ID，未指定时使用项目默认环境',
        )
    )
    op.create_index(
        'ix_test_runs_environment_id',
        'test_runs',
        ['environment_id'],
        unique=False,
    )
    op.create_foreign_key(
        'fk_test_runs_environment_id_project_environments',
        'test_runs',
        'project_environments',
        ['environment_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_test_runs_environment_id_project_environments',
        'test_runs',
        type_='foreignkey',
    )
    op.drop_index(
        'ix_test_runs_environment_id',
        table_name='test_runs',
    )
    op.drop_column('test_runs', 'environment_id')
    # ### end Alembic commands ###
