"""add_project_environments

Revision ID: ae72ff4fd9ce
Revises: 3100109ddd14
Create Date: 2026-07-06 10:26:36.068122+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae72ff4fd9ce'
down_revision: Union[str, None] = '3100109ddd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_environments',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='项目 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='环境名称，如 dev/test/prod'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为项目默认环境'),
    sa.Column('base_url', sa.String(length=2048), nullable=False, comment='API Base URL'),
    sa.Column('auth_type', sa.String(length=20), nullable=False, comment='认证类型'),
    sa.Column('auth_secret_encrypted', sa.Text(), nullable=True, comment='加密后的认证凭据'),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='非敏感认证配置，如 OAuth2 client_id、api_key 字段名'),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='额外请求头'),
    sa.Column('timeout_ms', sa.Integer(), nullable=False, comment='默认请求超时（毫秒）'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='项目环境配置表'
    )
    op.create_index(op.f('ix_project_environments_project_id'), 'project_environments', ['project_id'], unique=False)
    # 每个项目只能有一个默认环境
    op.create_index(
        'ix_project_environments_project_id_default',
        'project_environments',
        ['project_id'],
        unique=True,
        postgresql_where=sa.text('is_default = true')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_environments_project_id_default', table_name='project_environments')
    op.drop_index(op.f('ix_project_environments_project_id'), table_name='project_environments')
    op.drop_table('project_environments')
    # ### end Alembic commands ###
