"""add_dynamic_bearer_credentials

Revision ID: 8f4a2c1d5e90
Revises: ae72ff4fd9ce
Create Date: 2026-07-07 08:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4a2c1d5e90'
down_revision: Union[str, None] = 'ae72ff4fd9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project_environments',
        sa.Column(
            'auth_credentials_encrypted',
            sa.Text(),
            nullable=True,
            comment='加密后的认证原材料（如动态登录账号密码、OAuth2 client_secret）'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_environments', 'auth_credentials_encrypted')
    # ### end Alembic commands ###
